CREATE DATABASE sistema_farmacia;

USE sistema_farmacia;


CREATE TABLE FARM_REMEDIOS (
    REMD_ID INT AUTO_INCREMENT PRIMARY KEY,
    REMD_NOME VARCHAR(100) NOT NULL,
    REMD_FABRICANTE VARCHAR(100) NOT NULL,
    REMD_DESCRICAO VARCHAR(255) NOT NULL,
    REMD_PRECO decimal(10,2) NOT NULL,
    REMD_ESTOQUE INT NOT NULL
);

CREATE TABLE FARM_USUARIOS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(45) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(255) NOT NULL
);