CREATE DATABASE sistema_farmacia;

USE sistema_farmacia;


CREATE TABLE REMEDIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    FABRICANTE VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    PRECO decimal(10,2) NOT NULL,
    ESTOQUE INT NOT NULL
);
